/*
 * Introduction to Java base concepts
 * 
 * https://github.com/egalli64/jaba
 */
package com.example.jaba.m3.s5;

/**
 * Comparison operators
 */
public class Comparer {
    /**
     * Comparison operators on primitives, and equals() on references
     * 
     * @param args not used
     */
    public static void main(String[] args) {
        int alpha = 12;
        int beta = 21;
        int gamma = 12;
        System.out.println("alpha = " + alpha);
        System.out.println("beta = " + beta);
        System.out.println("gamma = " + gamma);

        boolean result = alpha < beta; // true
        System.out.println("alpha < beta? " + result);

        result = alpha < gamma; // false
        System.out.println("alpha < gamma? " + result);

        result = alpha <= gamma; // true
        System.out.println("alpha <= gamma? " + result);

        result = alpha > beta; // false
        System.out.println("alpha > beta? " + result);

        result = alpha > gamma; // false
        System.out.println("alpha > gamma? " + result);

        result = alpha >= gamma; // true
        System.out.println("alpha >= gamma? " + result);

        result = alpha == beta; // false
        System.out.println("alpha == beta? " + result);

        result = alpha == gamma; // true
        System.out.println("alpha == gamma? " + result);

        result = alpha != beta; // true
        System.out.println("alpha != beta? " + result);

        result = alpha != gamma; // false
        System.out.println("alpha != gamma? " + result);

        // For references, == is _not_ about the content
        String a = "solution";
        // A string generated by copy outside the String pool
        String b = new String(a);

        if (a != b) {
            System.out.println("The references a and b go to different objects");
        }

        // Also a string generated by concatenation is not in the String pool
        String c1 = "sol";
        String c2 = "ution";
        String c = c1 + c2;
        if (c != b && c != a) {
            System.out.println("a, b, and c are three different objects!");
        }

        // If the literal is already in the String pool, no new String is created
        // Two references to the same object
        String d = "solution";
        if (a == d) {
            System.out.println("The references a and d go to the same object");
        }

        if (a.equals(b) && b.equals(c) && c.equals(d)) {
            System.out.println("a, b, c, and d are all equals!");
        }
    }
}
